### PR TITLE
[1.10.x] Create DirectoryCreator helper class

### LINKED ISSUE #992: [Bug]: Test fails on a PHPStan test
### What Happened

Hello!

I'm trying to write a test for a [custom PHPStan Rule](https://phpstan.org/developing-extensions/testing) and the test keeps yielding a warning when using `artisan test` / `pest`. However, the test passes just fine when using the `phpunit` test runner which makes me think this is an issue with pest.

Any ideas what might be causing this?

image

CC: @ondrejmirtes 

Thanks!

### How to Reproduce

- Install new laravel app
- Install PHPStan
- Create a custom PHPStan rule and test
- Try to run test with pest

### Sample Repository

_No response_

### Pest Version

2.24

### PHP Version

8.2.10

### Operation System

Linux

### Notes

_No response_

### PR DESCRIPTION
**Pull request by calebdw**
Hello!

This is similar to https://github.com/phpstan/phpstan-src/pull/572 --- every other `mkdir` call is guarded by an `is_dir` check so I updated this to be consistent.

Thanks!

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
As far as PHP is concerned, this code is equivalent. You don't need to check is_dir before calling mkdir, the current code is fine.

I suspect the problem has a different root cause in Pest which should be addressed instead.

**Comment by calebdw** [comment]
Sure, I get that---likely having to do with how it's capturing warnings. But there's still three other calls to `mkdir` that are already guarded by an `is_dir` check so I feel either they should all be guarded or none of them should be guarded for consistency

**Comment by ondrejmirtes** [comment]
If we wanted to make this consistent everywhere, I'd welcome a new class `DirectoryCreator` with a static method that would be used in place of these calls.

**Comment by calebdw** [comment]
@ondrejmirtes done---please let me know if you'd like any other changes

File: src/Internal/FilesystemHelper.php [hunk 1]
```diff
@@ -0,0 +1,27 @@
+<?php declare(strict_types = 1);
+
+namespace PHPStan\Internal;
+
+use function clearstatcache;
+use function is_dir;
+use function mkdir;
+
+final class FilesystemHelper
```
Comment (ondrejmirtes) [inline src/Internal/FilesystemHelper.php]: Please name this class `DirectoryCreator` as I asked here: https://github.com/phpstan/phpstan-src/pull/2697#issuecomment-1784024859

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]

File: src/Internal/FilesystemHelper.php (hunk 1 above)
Comment (calebdw) [reply src/Internal/FilesystemHelper.php]: Done, I used `FilesystemHelper` because I figured other filesystem helpers could be added in the future

File: src/Cache/FileCacheStorage.php [hunk 2]
```diff
@@ -28,20 +26,12 @@ public function __construct(private string $directory)
...
-			clearstatcache();
-			if (is_dir($directory)) {
-				return;
-			}
-
-			$error = error_get_last();
-			throw new InvalidArgumentException(sprintf('Failed to create directory "%s" (%s).', $this->directory, $error !== null ? $error['message'] : 'unknown cause'));
-		}
+		$error = error_get_last();
+		throw new InvalidArgumentException(sprintf('Failed to create directory "%s" (%s).', $this->directory, $error !== null ? $error['message'] : 'unknown cause'));
```
Comment (ondrejmirtes) [inline src/Cache/FileCacheStorage.php]: Either we need to get rid of the specific error message here which relies on `error_get_last()` (leaks an implementation detail), or we need to throw a proper exception from DirectoryCreator, and surround each call with a try-catch.

I'd actually be in favour of the exception, because using return `bool` values to signal an error isn't great.

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]

File: src/Cache/FileCacheStorage.php (hunk 2 above)
Comment (calebdw) [reply src/Cache/FileCacheStorage.php]: Done

File: src/Internal/DirectoryCreator.php [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+	/**
+	 * @throws InvalidArgumentException
+	 */
+	public static function ensureDirectoryExists(
+		string $directory,
+		int $mode = 0755,
+		bool $recursive = true,
+	): void
+	{
+		if (is_dir($directory)) {
```
Comment (staabm) [inline src/Internal/DirectoryCreator.php]: since we have to use error suppressing in the below `mkdir()` calls, IMO we should not use `is_dir` here, which produces unnecessary IO

File: src/Internal/DirectoryCreator.php [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+use InvalidArgumentException;
+use function clearstatcache;
+use function is_dir;
+use function mkdir;
+
+final class DirectoryCreator
+{
+
+	/**
+	 * @throws InvalidArgumentException
```
Comment (ondrejmirtes) [inline src/Internal/DirectoryCreator.php]: Please create, throw and catch a specific exception, like `DirectoryCreatorException`.

File: src/Internal/DirectoryCreator.php (hunk 3 above)
Comment (ondrejmirtes) [reply src/Internal/DirectoryCreator.php]: Agreed, the first if can be removed

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]

File: src/Internal/DirectoryCreator.php (hunk 3 above)
Comment (calebdw) [reply src/Internal/DirectoryCreator.php]: That defeats the whole purpose of me submitting this PR in the first place... yes error suppression is used but an unnecessary warning is still generated which can cause issues for clients. There have been previous issues and PRs to add the `is_dir` check to avoid the warning being generated

Comment (ondrejmirtes) [reply src/Internal/DirectoryCreator.php]: I've previously told you the root issue needs to be fixed in Pest. PHPStan's source code needs to make sense on its own. Otherwise it's not really good engineering and the code would be very brittle.

Comment (calebdw) [reply src/Internal/DirectoryCreator.php]: I can remove, but I'm just pointing out that I'm not the first person this has caused issues with and who has tried to add the dir existence check

File: src/Internal/DirectoryCreator.php (hunk 4 above)
Comment (calebdw) [reply src/Internal/DirectoryCreator.php]: done

File: src/Internal/DirectoryCreator.php (hunk 3 above)
Comment (calebdw) [reply src/Internal/DirectoryCreator.php]: removed

File: src/Internal/DirectoryCreator.php [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+	): void
+	{
+		if (@mkdir($directory, $mode, $recursive)) {
+			return;
+		}
+
+		clearstatcache();
+
+		if (!is_dir($directory)) {
+			throw new DirectoryCreatorException($directory);
```
Comment (ondrejmirtes) [inline src/Internal/DirectoryCreator.php:28]: Would be great to actually use `error_get_last()` here and write a nice error message like the one you deleted in `makeDir`.

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
After this it's good to merge 👍

File: src/Internal/DirectoryCreator.php (hunk 5 above)
Comment (calebdw) [reply src/Internal/DirectoryCreator.php:28]: done

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by ondrejmirtes** [comment]
Just did this to improve compatibility with PHPUnit and PHP-Parser 5: https://github.com/phpstan/phpstan-src/commit/9dac90dfd5fc809dd84fdac0532ecd51c6ae66bf
