### PR TITLE
`array_key_exist` inference is lost when adding a false condition

### LINKED ISSUE #100: AssertArrayHasKey seems to be not supported
Hi @ondrejmirtes, I just got an issue with my tests saying that an offset does not exist in an array.
I tried to add a `assertArrayHasKey` check, without success.

I think this assert is not handle by this plugin, am I wrong ?

I'll try to do a PR in order to add the support, I think I'll be able to copy the way `isArray` works.
https://github.com/phpstan/phpstan-phpunit/blob/master/src/Type/PHPUnit/Assert/AssertTypeSpecifyingExtensionHelper.php#L158

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/phpstan/phpstan/issues/11276

fixes https://github.com/phpstan/phpstan-phpunit/issues/100

### CODE REVIEW

**Comment by VincentLanglet** [comment]
So no issue with this PR ?

Thanks for finding it !

**Comment by staabm** [comment]
I think it works (but did not re-use your previous implementation)

File: src/Analyser/TypeSpecifier.php [hunk 1]
```diff
@@ -663,7 +663,24 @@ public function specifyTypesInCondition(
 			$leftTypes = $this->specifyTypesInCondition($scope, $expr->left, $context)->setRootExpr($expr);
 			$rightScope = $scope->filterByFalseyValue($expr->left);
 			$rightTypes = $this->specifyTypesInCondition($rightScope, $expr->right, $context)->setRootExpr($expr);
-			$types = $context->true() ? $leftTypes->normalize($scope)->intersectWith($rightTypes->normalize($rightScope)) : $leftTypes->unionWith($rightTypes);
+
+			if ($context->true()) {
+				if (
+					$scope->getType($expr->left)->isFalse()->yes()
```
Comment (ondrejmirtes) [inline src/Analyser/TypeSpecifier.php]: My head hurts 😅 

I think all the `isTrue`/`isFalse` calls should do `toBoolean()` beforehand.

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]

File: src/Analyser/TypeSpecifier.php (hunk 1 above)
Comment (staabm) [reply src/Analyser/TypeSpecifier.php]: great catch. fixed.

thank you.

Comment (staabm) [reply src/Analyser/TypeSpecifier.php]: hmm maybe we should have a `$type->isFalse()->yes()`/`$type->isTrue()->yes()` to `$type->toBoolean()->isFalse()->yes()`/`$type->toBoolean()->isTrue()->yes()` mutator.

it would make us aware of false/falsey coverage

File: .github/workflows/tests.yml [hunk 2]
```diff
@@ -240,6 +240,7 @@ jobs:
         run: |
           php build-infection/bin/infection-config.php \
             --source-directory='build/PHPStan/Build' \
+            --timeout=180 \
```
Comment (staabm) [inline .github/workflows/tests.yml]: in the worst case infection needs enough time to run the full test-suite.
otherwise mutants are considered 'skipped', which we saw in CI:

grafik


this setting means: "how many seconds can infection spent on a single mutant"

Comment (staabm) [reply .github/workflows/tests.yml]: opened a new ticket, as we need more information to proceed.
https://github.com/infection/infection/issues/2510

even after raising the timeout to 300 it still times out.
so at phpstan-src repo we are so slow, that we can't even check 3 mutants in 15minutes CI runtime.

we can merge for now

Comment (staabm) [reply .github/workflows/tests.yml]: lets fix this in a separate PR

**Comment by ondrejmirtes** [comment]
Make a build-infection issue for the new mutator idea 😊

**Comment by ondrejmirtes** [comment]
Thank you!
